name: CI

on:
  push:
    branches:
      - main

jobs:
  pipelineJava17:
  #Organization env variable name ORG
    uses: challenge-devsu/devops/pipeline/java.yml@main
    #uses: ${{ env.ORG }}/devops/pipeline/java.yml@main
    with:
      holis: "holis"
